{
 "title": "Single-node",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Nombre de noeud alloué",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "RawData",
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "slurm_user_jobs_nodes_alloc",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Nombre de jobs en cours d'execution",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "RawData",
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "slurm_user_jobs_running",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Nombre de job en cours de ré-allocation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "RawData",
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "slurm_user_jobs_requeued",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Nombre de job en attente d'allocation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "RawData",
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "slurm_user_jobs_pending",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Nombre de cpu utilisé",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "RawData",
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "slurm_user_jobs_cpus_alloc",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "mémoire alloué par slurm pour le job",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "RawData",
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "slurm_user_jobs_memory_alloc",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Moyenne charge CPU sur 1 min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 6 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "RawData",
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "node_load1",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU bloqué en attente d'I/O",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "RawData",
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "node_procs_blocked",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Nombre de seconde d'attente processus -> cause d'IO",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "RawData",
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "node_pressure_io_waiting_seconds_total",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Nombre de socket en cours d'utilisation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "RawData",
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "node_sockstat_sockets_used",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Nombre de seconde que les processus ont attendu le CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "RawData",
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "node_pressure_cpu_waiting_seconds_total",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Mémoire disponible",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "RawData",
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "node_memory_MemAvailable_bytes",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Moyenne charge CPU sur 15 min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "RawData",
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "node_load15",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Moyenne d'IO en cours",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "RawData",
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "node_disk_io_now",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Temps moyenne passé à la lecture",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "RawData",
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "node_disk_read_time_seconds_total",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Mémoire totale",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "RawData",
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "node_memory_MemTotal_bytes",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Fréquence moyenne des CPUs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "RawData",
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "node_cpu_scaling_frequency_hertz",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Température moyenne CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "RawData",
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "node_thermal_zone_temp",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Temps moyenne passé à l'écriture",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "RawData",
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "node_disk_write_time_seconds_total",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}